//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRECHEPROJET
{
    using System;
    using System.Collections.Generic;
    
    public partial class enfant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enfant()
        {
            this.contrat = new HashSet<contrat>();
        }
    
        public int IDenfant { get; set; }
        public string NomEnfant { get; set; }
        public string PrenomEnfant { get; set; }
        public Nullable<System.DateTime> Datedenaissance { get; set; }
        public string Ville { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contrat> contrat { get; set; }
    }
}
