//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRECHEPROJET
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mydbEntities15 : DbContext
    {
        public mydbEntities15()
            : base("name=mydbEntities15")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<acceuil> acceuil { get; set; }
        public virtual DbSet<contrat> contrat { get; set; }
        public virtual DbSet<creche> creche { get; set; }
        public virtual DbSet<enfant> enfant { get; set; }
        public virtual DbSet<unite> unite { get; set; }
    }
}
