//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRECHEPROJET
{
    using System;
    using System.Collections.Generic;
    
    public partial class unite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public unite()
        {
            this.contrat = new HashSet<contrat>();
        }
    
        public int IDUnite { get; set; }
        public string NomUnite { get; set; }
        public int CRECHE_IDCreche { get; set; }
        public int AlphaUnite { get; set; }
        public int RougeUnite { get; set; }
        public int VertUnite { get; set; }
        public int Bleu_Unite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contrat> contrat { get; set; }
        public virtual creche creche { get; set; }
    }
}
